[book]
authors = ["zuowenjian"]
language = "en"
multilingual = true
src = "./"
title = "dayu-veyron"

[preprocessor.theme]
content-max-width = "80%"
pagetoc = true
pagetoc-width = "15%"
root-font-size = "70%"
sidebar-width = "120px"
turn-off = true

[output.html]
additional-css = ["theme/simple-lightbox.css", "theme/theme.css", "theme/pagetoc.css"]
additional-js = ["theme/simple-lightbox.min.js", "theme/theme.js", "theme/pagetoc.js"]

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = true

[build]
build-dir = "_html"
