[log]
level = "debug"
output = "Console"
output_path = "./logs/"

[web]
host = "0.0.0.0"
port = 8080

[repo]
wpl_rule_repo = "/Users/tangxiangyan/Documents/projects/wp/git/wp-rule/models/wpl"
oml_rule_repo = "/Users/tangxiangyan/Documents/projects/wp/git/wp-rule/models/oml"
